### ISSUE TITLE
`to_s` and `p` names are too short

### ISSUE THREAD

**Issue by sarna** [moonglum/halunke#12]
Almost all functions (? not sure about the terminology) in Halunke are whole words, except these two. You can look at any function and know what it's doing - `reverse` reverses a string, `merge` merges dictionaries etc. With `to_s` and `p` it's not that clear.

**Comment by moonglum** [comment]
You are absolutely right. This is directly copied from Ruby – which mostly has pretty good method names. But those are not so good. So `to_s` will be renamed to `to_string`. Do you have a suggestion for `p`? It's like puts, but creates debug output 🤔

**Comment by sarna** [comment]
`puts_debug` is kinda long. Maybe `dump`?

**Comment by moonglum** [comment]
What do you think about `examine`?

**Comment by sarna** [comment]
I like it :)

**Comment by sarna** [comment]
Thank you for making this language, it's absolutely rad :^)

**Comment by moonglum** [comment]
Thanks for your kind words ❤️ I need to work on it again – your words are a great encouragement to do so 😊

**Comment by moonglum** [comment]
@sarna I just released https://github.com/moonglum/halunke/releases/tag/v0.8.0 which addresses this 👍 Thank you again for your feedback 🙇

**Comment by sarna** [comment]
Well done! I'll check it out once I get some personal stuff sorted out :^) I'm excited

**Comment by moonglum** [comment]
Awesome 👍
